Add gen-from-keys to cmd
ameshkov/dnscrypt pull request #5
Opened 2021-02-01 11:19 UTC by sdbochkarev

Added command for generate dnscrypt configuration from both dnscrypt and server private keys

2021-02-01 11:23 UTC, ameshkov commented on cmd/gen_from_keys.go
> +// GenerateArgs - "generate" command arguments
комментарий неверный

2021-02-01 11:26 UTC, ameshkov requested changes
Еще и билд сломался на трэвисе.

2021-02-01 11:26 UTC, ameshkov commented on cmd/main.go
> +	GenFromKeys GenFromKeysArgs `command:"gen-from-keys" description:"Generate DNSCrypt server configuration from .key files"`
Из каких .key files? Назови `convert-dnscrypt-wrapper` и в описании напиши, что это конвертация из конфигурации dnscrypt-wrapper в нашу

2021-02-01 11:26 UTC, ameshkov commented on cmd/gen_from_keys.go
> +	privateCrypt := getFileContent(args.DNSCryptKeyFile)
Тут не помешает валидация, что это корректные ключи.

2021-02-01 11:26 UTC, ameshkov commented on cmd/gen_from_keys.go
> +	rc.PublicKey = dnscrypt.HexEncodeKey(privateCrypt[len(privateCrypt)/2:])
Поищи по коду в этом проекте как правильно из приватного ключа получать публичный

2021-02-01 11:26 UTC, ameshkov commented on cmd/gen_from_keys.go
> +	DNSCryptKeyFile string `short:"d" long:"crypt-key" description:"DNSCryptResolver private key filename" required:"true"`
Это какой ключ? Которым сертификат подписывается или ResolverSk?

Нейминг должен соответствовать тому, что мы генерируем в итоге.

2021-02-01 11:27 UTC, ameshkov commented
И нужно дополнить README, добавить описание, как сконвертировать существующий конфиг dnscrypt-wrapper в конфиг нашей утилиты.

2021-02-01 15:37 UTC, sdbochkarev commented on cmd/gen_from_keys.go
> +	privateCrypt := getFileContent(args.DNSCryptKeyFile)
Пока не нашёл способов, кроме проверки длины.

2021-02-01 16:29 UTC, ameshkov requested changes
Еще по-мелочи надо поправить

2021-02-01 16:29 UTC, ameshkov commented on README.md
> +    * [Making config from dnscrypt-wrapper generated keys](convertfromwrapper)
Converting `dnscrypt-wrapper` configuration

2021-02-01 16:29 UTC, ameshkov commented on cmd/convert_dnscrypt_wrapper.go
> +	ResolverSkFile string `short:"r" long:"resolver-sk-key" description:"Short-term private key file for encrypt/decrypt dns queries" required:"true"`
Short-term privacy key file for encrypting/decrypting DNS queries.

2021-02-01 16:29 UTC, ameshkov commented on cmd/convert_dnscrypt_wrapper.go
> +	ResolverSkFile string `short:"r" long:"resolver-sk-key" description:"Short-term private key file for encrypt/decrypt dns queries" required:"true"`
Думаю не нужно делать его обязательным - при необходимости пусть генерируется

2021-02-01 16:29 UTC, ameshkov commented on cmd/convert_dnscrypt_wrapper.go
> +	ResolverSkFile string `short:"r" long:"resolver-sk-key" description:"Short-term private key file for encrypt/decrypt dns queries" required:"true"`
Желательно названия параметров делать совпадающими с названиями соответствующих полей в config.yaml. Этот например - `resolver-secret`

2021-02-01 16:29 UTC, ameshkov commented on cmd/convert_dnscrypt_wrapper.go
> +	rc.ResolverPk = dnscrypt.HexEncodeKey(getResolverPk(resolverSecret))
`rc` бы еще завалидировать, там вроде есть метод для проверки

2021-02-01 16:29 UTC, ameshkov commented on cmd/convert_dnscrypt_wrapper.go
> +// getResolverPk - generates public key corresponding to private
публичный кюч все-таки из приватного не генерируется, а вычисляется или получается.

2021-02-01 16:33 UTC, ameshkov commented
И билд все еще фейлится

2021-02-02 07:40 UTC, sdbochkarev commented on README.md
> +./dnscrypt convert-dnscrypt-wrapper \
по остальным командам тогда тоже на --help заменить, может? а то будет неодинаково

2021-02-02 08:01 UTC, sdbochkarev commented on cmd/convert_dnscrypt_wrapper.go
> +	rc.ResolverPk = dnscrypt.HexEncodeKey(getResolverPk(resolverSecret))
@ameshkov Валидирую сейчас через создание серта и проверку его подписи этим публичным ключом, но выглядит как бесполезная проверка, поскольку на основе конфига создаю сертификат, подписываю публичным ключом, а затем проверяю, что сертификат подписан именно этим ключом. И проверка срока действия сертификата, которая тоже кажется бесполезной, поскольку серт создаётся от текущей даты. Я бы всё-таки убрал это.

2021-02-02 08:51 UTC, ameshkov requested changes

2021-02-02 08:51 UTC, ameshkov commented on README.md
> +-p, --private-key=     DNSCrypt resolver private key that is used for signing certificates
Момент упустили в описании параметров. Это ведь `path to the DNSCrypt resolver private key file`

2021-02-02 08:51 UTC, ameshkov commented on README.md
> +-p, --private-key=     DNSCrypt resolver private key that is used for signing certificates
Второй параметр, соответственно, тоже путь

2021-02-02 08:51 UTC, ameshkov commented on README.md
> +```
Давай в остальных командах действительно тоже `--help`, чтобы выглядели одинаково

2021-02-02 08:51 UTC, ameshkov commented on README.md
> +Keys generated using dnscrypt-wrapper can be converted to config.yaml by running the command:
dnscrypt-wrapper сделай ссылкой на https://github.com/cofyc/dnscrypt-wrapper

2021-02-02 10:54 UTC, ameshkov approved these changes

2021-02-02 10:54 UTC, merged